spring:
  datasource:
    primary:
      jdbcUrl: jdbc:h2:mem:primarydb
      driver-class-name: org.h2.Driver
      username: sa
      password:
    secondary:
      jdbcUrl: jdbc:h2:mem:secondarydb
      driver-class-name: org.h2.Driver
      username: sa
      password:
  application:
    name: demo